image: runmymind/docker-android-sdk
pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew clean assembleProdRelease
          - bash ./gradlew testProdReleaseUnitTest
  custom:
    crashlytics:
      - step:
          script:
            - bash ./gradlew crashlyticsUploadDistributionProdRelease
