image: runmymind/docker-android-sdk
pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew clean assembleProdRelease
          - bash ./gradlew testProdReleaseUnitTest
  custom:
    publish_to_fabric_beta:
      - step:
          script:
            - ./pipelines/oAuthGit.sh
            - git init
            - git config user.name "CI Robot"
            - git config user.email "robot@your.service"
            - bash ./gradlew clean assembleProdRelease
            - bash ./gradlew testProdReleaseUnitTest
            - bash ./gradlew crashlyticsUploadDistributionProdRelease
            - git tag "build-$BITBUCKET_BUILD_NUMBER"
            - bash ./gradlew incrementVersionPatch
            - git commit -a -m "Bump version"
            - git push -u origin --tags