image: runmymind/docker-android-sdk
pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew clean assembleProdDebug
          - bash ./gradlew testProdDebugUnitTest
