image: runmymind/docker-android-sdk
pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew clean assembleProdRelease
          - bash ./gradlew testProdReleaseUnitTest
  custom:
    push_to_crashlytics_beta:
      - step:
          script:
            - bash ./gradlew clean assembleProdRelease
            - bash ./gradlew testProdReleaseUnitTest
            - bash ./gradlew crashlyticsUploadDistributionProdRelease
            - git tag "build-$BITBUCKET_BUILD_NUMBER"
            - git push --tags
