image: runmymind/docker-android-sdk
pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - git remote -v
          - git tag -l
          - git log | head
          - git tag hello
          - git tag -l
          - touch a.txt
          - git add a.txt
          - git status
          - git commit "Message"
          - git log | head
          - git push origin --tags
  custom:
    push_to_crashlytics_beta:
      - step:
          script:
            - bash ./gradlew clean assembleProdRelease
            - bash ./gradlew testProdReleaseUnitTest
            - bash ./gradlew crashlyticsUploadDistributionProdRelease
            - git tag "build-$BITBUCKET_BUILD_NUMBER"
            - git push --tags
